name: dart_only_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  hooks: ^0.20.1
  native_toolchain_rs: ^0.1.2+3

dev_dependencies:
  ffigen: ^20.0.0
  test: ^1.26.2
